#include "hmm.h"

#include <iostream>
#include <iomanip>
#include <array>

#include <Eigen/Dense>
#include <unsupported/Eigen/CXX11/Tensor>

#include "distributions.h"
#include "data_loader.h"
#include "utils.h"


/*
 * Run forward algorithm
 */
void HMM::forward(Eigen::MatrixXd& alpha, Eigen::VectorXd& c, const Eigen::MatrixXd& B) {
    alpha.col(0) = B.col(0).array() * start_priors.array();
    
    // scale alpha
    c(0) = 1.0 / alpha.col(0).sum();
    alpha.col(0) *= c(0);
    
    for (size_t t = 1; t < alpha.cols(); ++t) {
        Eigen::VectorXd prev = transp.transpose() * alpha.col(t - 1);
        alpha.col(t) = B.col(t).array() * prev.array();
        
        // scale alpha
        c(t) = 1.0 / alpha.col(t).sum();
        alpha.col(t) *= c(t);
    }
}

/*
 * Run backward algorithm
 */
void HMM::backward(Eigen::MatrixXd& beta, Eigen::VectorXd& c, const Eigen::MatrixXd& B) {
    size_t T = beta.cols() - 1;
    beta.col(T) = c(T) * end_priors.array();

    for (size_t t = T - 1; t != SIZE_MAX; --t) {
        Eigen::VectorXd next = beta.col(t + 1).array() * B.col(t + 1).array();

        beta.col(t) = transp * next;
        beta.col(t) *= c(t);
    }
}

/*
 * Compute gamma
 */
void HMM::compute_gamma(Eigen::MatrixXd& gamma, const Eigen::MatrixXd& alpha, const Eigen::MatrixXd& beta) {
    gamma = alpha.array() * beta.array();
    gamma = gamma.array().rowwise() / gamma.colwise().sum().array();
}

/*
 * Compute xi over every timestep in the observation sequence
 */
void HMM::compute_xi(Eigen::Tensor<double, 3>& xi, const Eigen::MatrixXd& alpha, const Eigen::MatrixXd& beta, const Eigen::MatrixXd& B) {
    size_t T = xi.dimension(0);
    for(size_t t = 0; t < T; ++t) {
        Eigen::VectorXd trans_to = beta.col(t + 1).array() * B.col(t + 1).array();
        Eigen::MatrixXd trans_from = transp.array().colwise() * alpha.col(t).array();
        
        Eigen::MatrixXd xi_t = trans_from.array().rowwise() * trans_to.array().transpose();
        double total_sum = xi_t.sum();
        if (total_sum > utils::FLOOR_VAL) {
            xi_t /= total_sum;
        }
        else {
            utils::CppLogger::log_warning() << "Baum-Welch Underflow/Impossible Path at timestep t = " << t
                      << " (sum = " << total_sum << "). "
                      << "The observation sequence cannot be generated by the current model parameters. "
                      << "Assigning uniform fallback to avoid NaNs.\n";

            // Fallback strategy to protect the rest of the matrix math
            xi_t.setConstant(1.0 / (xi_t.rows() * xi_t.cols()));
        }
        
        xi.chip(t, 0) = Eigen::TensorMap<const Eigen::Tensor<const double, 2>>(
            xi_t.data(),
            xi_t.rows(),
            xi_t.cols()
        );
    }
}

/*
 * update params
 */
void HMM::update_params(const Eigen::MatrixXd& gamma, const Eigen::Tensor<double, 3>& xi, const Eigen::VectorXd& obs) {
    // compute priors (start/end)
    start_priors = gamma.col(0);
    end_priors = gamma.col(gamma.cols() - 1);
    
    // compute gamma normalization constant for each row (floor it to avoid div by 0 issues)
    Eigen::VectorXd gamma_rownorm = gamma.rowwise().sum().cwiseMax(utils::FLOOR_VAL);
    Eigen::VectorXd gamma_rownorm_xi = gamma.leftCols(gamma.cols() - 1).rowwise().sum().cwiseMax(utils::FLOOR_VAL);
    
    // sum xi over time
    std::array<int, 1> time_dim = {0};
    Eigen::Tensor<double, 2> xi_sum_t = xi.sum(time_dim);
    
    // compute new transp
    Eigen::Map<Eigen::MatrixXd> xi_sum(xi_sum_t.data(), xi.dimension(1), xi.dimension(2));
    transp = xi_sum.array().colwise() / gamma_rownorm_xi.array();
    // transp = transp.array().rowwise() / transp.rowwise().sum().array();
    
    // compute mean
    Eigen::VectorXd w_obs_mean = (gamma * obs).array() / gamma_rownorm.array();
    
    // compute variance and std dev
    Eigen::MatrixXd w_obs_mean_mat = w_obs_mean.replicate(1, obs.size());
    Eigen::MatrixXd deviations = w_obs_mean_mat.rowwise() - obs.transpose();
    
    Eigen::MatrixXd sq_deviations = deviations.array().square();
    Eigen::MatrixXd sum_sq_deviations = (sq_deviations.array() * gamma.array()).rowwise().sum();
    
    Eigen::VectorXd w_obs_var = sum_sq_deviations.array() / gamma_rownorm.array();
    Eigen::VectorXd w_obs_std_dev = w_obs_var.array().sqrt().cwiseMax(utils::FLOOR_VAL);
    
    // reassign mean and std dev of all states
    emissions.means = w_obs_mean;
    emissions.std_devs = w_obs_std_dev;
}

/*
 * initialize hmm model.
 */
void HMM::initialize_model() {
    // fill out prior probs
    std::vector<double> start_priors_vec(n_states);
    start_priors_vec[0] = 1.0;
    start_priors = Eigen::Map<Eigen::VectorXd>(
        start_priors_vec.data(),
        start_priors_vec.size()
    );

    std::vector<double> end_priors_vec(n_states);
    end_priors_vec[n_states - 1] = 1.0;
    end_priors = Eigen::Map<Eigen::VectorXd>(
        end_priors_vec.data(),
        end_priors_vec.size()
    );
    
    transp.setZero(n_states, n_states);
    // fill out transp matrix
    for (size_t i = 0; i < n_states; ++i) {
        for (size_t j = 0; j < n_states; ++j) {
            if (j == i || j == i + 1) transp(i,j) = 0.5;
        }
    }

    utils::CppLogger::log_debug() << start_priors;
    utils::CppLogger::log_debug() << end_priors;
    utils::CppLogger::log_debug() << transp;
    utils::CppLogger::log_debug() << emissions;
    // emission probs are filled when calling the constructor
}

/*
 * single iteration of baum welch
 */
void HMM::baum_welch(const Eigen::VectorXd& obs) {
    size_t T = obs.size();

    Eigen::MatrixXd alpha = Eigen::MatrixXd::Zero(n_states, T);
    Eigen::MatrixXd beta = Eigen::MatrixXd::Zero(n_states, T);

    Eigen::MatrixXd B = emissions.pdf(obs);

    Eigen::VectorXd c = Eigen::VectorXd::Zero(T);
    forward(alpha, c, B);
    backward(beta, c, B);
    
    Eigen::MatrixXd gamma = Eigen::MatrixXd::Zero(n_states, T);
    compute_gamma(gamma, alpha, beta);

    Eigen::Tensor<double, 3> xi(T - 1, n_states, n_states);
    compute_xi(xi, alpha, beta, B);

    update_params(gamma, xi, obs);
}

// overload ostream for clean print
std::ostream& operator<<(std::ostream& os, const HMM& hmm) {
    os << "Start prior probabilities: \n";
    os << hmm.get_start_priors() << "\n\n";

    os << "End prior probabilities: \n";
    os << hmm.get_end_priors() << "\n\n";

    os << "Transition probabilities \n";
    os << hmm.get_transp() << "\n\n";
    
    os << "Emission probabilities: \n";
    os << hmm.get_emissions() << "\n\n";

    return os;
}

