#include "hmm.h"

#include <iostream>
#include <fstream>
#include <iomanip>
#include <array>

#include <Eigen/Dense>
#include <unsupported/Eigen/CXX11/Tensor>

#include "distributions.h"
#include "data_loader.h"
#include "utils.h"

/**************************************** PRIVATE FXN ****************************************/

/*
 * Run forward algorithm
 *
 * We fill the first col of alpha using the emissions matrix
 * and start priors. Later cols use the transition probability
 * from previous possible states, the emissions matrix and 
 * the inductive probability computed until that point (as a prior).
 *
 * We scale alpha at each timestep (normalizing by the col sum)
 * and store it in Eigen::VectorXd c. It is used by the backward
 * algorithm as well. When gamma and xi are computed, the scalars
 * cancel so that parameter updates are unaffected.
 */
void HMM::forward(Eigen::MatrixXd& alpha, Eigen::VectorXd& c, const Eigen::MatrixXd& B) {
    alpha.col(0) = B.col(0).array() * start_priors.array();
    
    // scale alpha
    c(0) = 1.0 / alpha.col(0).sum();
    alpha.col(0) *= c(0);
    
    for (size_t t = 1; t < alpha.cols(); ++t) {
        Eigen::VectorXd prev = transp.transpose() * alpha.col(t - 1);
        alpha.col(t) = B.col(t).array() * prev.array();
        
        // scale alpha
        c(t) = 1.0 / alpha.col(t).sum();
        alpha.col(t) *= c(t);
    }
}

/*
 * Run backward algorithm
 *
 * We fill the final col of beta using the alpha scalar value c(T)
 * and the end priors array.
 *
 * We iterate backwards over timesteps computing the new col of beta
 * using transition probabilities of transitioning to the next state,
 * emissions for the next state and the inductive prior from the next state.
 * We then scale that column of beta using c(t).
 */
void HMM::backward(Eigen::MatrixXd& beta, Eigen::VectorXd& c, const Eigen::MatrixXd& B) {
    size_t T = beta.cols() - 1;
    beta.col(T) = c(T) * end_priors.array();

    for (size_t t = T - 1; t != SIZE_MAX; --t) {
        Eigen::VectorXd next = beta.col(t + 1).array() * B.col(t + 1).array();

        beta.col(t) = transp * next;
        beta.col(t) *= c(t);
    }
}

/*
 * Compute gamma
 *
 * Gamma is the probability of passing through a given state
 * for the sequence being examined. It combined forwards and backwards
 * probabilities to compute the probability of being in a given state
 * at a timestep t for that sequence (considering all state sequences passing
 * throuh that state).
 */
void HMM::compute_gamma(Eigen::MatrixXd& gamma, const Eigen::MatrixXd& alpha, const Eigen::MatrixXd& beta) {
    gamma = alpha.array() * beta.array();
    gamma = gamma.array().rowwise() / gamma.colwise().sum().array();
}

/*
 * Compute xi over every timestep in the observation sequence.
 */
void HMM::compute_xi(Eigen::Tensor<double, 3>& xi, const Eigen::MatrixXd& alpha, const Eigen::MatrixXd& beta, const Eigen::MatrixXd& B) {
    size_t T = xi.dimension(0);
    size_t num_lowsums = 0;
    
    for(size_t t = 0; t < T; ++t) {
        Eigen::VectorXd trans_to = beta.col(t + 1).array() * B.col(t + 1).array();
        Eigen::MatrixXd trans_from = transp.array().colwise() * alpha.col(t).array();
        
        Eigen::MatrixXd xi_t = trans_from.array().rowwise() * trans_to.array().transpose();
        double total_sum = xi_t.sum();
        if (total_sum > HMM::FLOOR_VAL) {
            xi_t /= total_sum;
        }
        else {
            // Fallback strategy to protect the rest of the matrix math
            xi_t.setConstant(1.0 / (xi_t.rows() * xi_t.cols()));
            num_lowsums++;
        }
        
        xi.chip(t, 0) = Eigen::TensorMap<const Eigen::Tensor<const double, 2>>(
            xi_t.data(),
            xi_t.rows(),
            xi_t.cols()
        );
    }
    
    if (num_lowsums > 0 && !ignore_warnings) {
        utils::CppLogger::log_warning() << "Baum-Welch Underflow/Impossible Path at " << num_lowsums << " timesteps. "
                  << "The observation sequence cannot be generated by the current model parameters. "
                  << "Assigning uniform fallback to avoid NaNs.\n";
    }
}

/*
 * update accumulators
 */
void HMM::update_accumulators(const Eigen::MatrixXd& gamma, const Eigen::Tensor<double, 3>& xi, const Eigen::VectorXd& obs) {
    start_prior_acc += gamma.col(0);
    end_prior_acc += gamma.col(gamma.cols() - 1);
    
    gamma_acc += gamma.rowwise().sum();
    std::array<int, 1> time_dim = {0};
    Eigen::Tensor<double, 2> xi_sum_t = xi.sum(time_dim);
    Eigen::Map<Eigen::MatrixXd> xi_sum(xi_sum_t.data(), xi.dimension(1), xi.dimension(2));
    xi_acc += xi_sum;
    
    obs_acc.noalias() += (gamma * obs);
    obs_sq_acc.noalias() += (gamma * obs.array().square().matrix());
}

/**************************************** PUBLIC FXN ****************************************/

/*
 * initialize hmm model.
 */
// void HMM::initialize_model() {
//     log_info() << "initialized model via flat start";
// }

/*
 * Loads hmm from config file
 * For now, config file should contain
 *  -- start priors
 *  -- end priors
 *  -- transp matrix
 */
void HMM::load_from_config(fs::path config_file) {
    log_info() << "Loading config file: " << config_file.filename();
    std::ifstream file(config_file); 
    
    if (!file.is_open()) {
        log_error() << "Error: Could not open file at " << config_file;
        log_error() << "Could not load HMM config.";
        return;
    }
    
    std::string line;
    std::vector<double> flat_data;
    
    size_t num_rows = 0;
    size_t num_cols = 0;
    
    while (std::getline(file, line)) {
        if (line.empty()) {
            log_error() << "Error: Found empty line in config file " << config_file;
            log_error() << "Could not load HMM config.";
            return;
        }
        
        std::stringstream ss(line);
        double value;
        size_t current_row_cols = 0;
        
        while (ss >> value) {
            flat_data.push_back(value);
            current_row_cols++;
        }
        
        if (current_row_cols != n_states) {
            log_error() << "Error. Config must have " << n_states << " cols.";
            log_error() << "Could not load " << config_file;
            return;
        }
        num_rows++;
    }

    if (num_rows - 2 != n_states) {
        log_error() << "Error. Config must have " << n_states + 2 << " rows.";
        log_error() << "Could not load " << config_file;
        return;
    }
    
    // Map first row into start priors
    const double* start = flat_data.data();
    start_priors = Eigen::Map<const Eigen::VectorXd>(start, n_states);
    
    // Map next row into end priors
    start += n_states;
    end_priors = Eigen::Map<const Eigen::VectorXd>(start, n_states);
    
    // Map and copy the transp table
    start += n_states;
    using mmatrix = Eigen::Map<const Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>>;
    transp = mmatrix(start, n_states, n_states);
    
    log_info() << "Successfully loaded start priors, end priors and transp from: " << config_file.filename();
}

/*
 * Resets the initialization accumulators for mean
 * and variance. Sets them to 0 so they can be summed
 * and accumulate observation data.
 *
 * The counter for averaging is also reset.
 */
void HMM::init_reset_accumulators() {
    init_means_acc.setZero(n_states);
    init_std_dev_acc.setZero(n_states);
    init_obs_count_acc.setZero(n_states);
}

/*
 * Initialize the Hidden Markov Model. For now it just initializes
 * emissions. The user is expected to initialize transp and start/end
 * priors.
 *
 * The user should call init_reset_accumulators before calling
 * this function.
 */
void HMM::init_accumulate(const Eigen::VectorXd& obs, const std::vector<std::string>& labels) {
    size_t seglen = obs.size() / n_states;
    if (seglen <= HMM::MIN_FRAMES_PER_STATE) {
        log_error() << "There are too few observations per state.";
        log_error() << "Skipping this sequence";
        return;
    }
    
    log_debug() << "init_accumulate: obs vec size: " << obs.size();
    // iterate until last state
    for (size_t i = 0; i < n_states; ++i) {
        size_t start = i * seglen;
        if (i == n_states - 1) {
            // since seglen is originally from floor division
            // we grab the rest of the array for the last it.
            seglen = obs.size() - start;
        }
        
        log_debug() << "init_accumulate start: " << start;
        log_debug() << "init_accumulate seglen: " << seglen;
        
        init_means_acc(i) += obs.segment(start, seglen).sum();
        init_std_dev_acc(i) += obs.segment(start, seglen).array().square().sum();
        init_obs_count_acc(i) += seglen;
    }
}

void HMM::init_summarize() {
    Eigen::VectorXd init_obs_count_acc_dbl = init_obs_count_acc.cast<double>();
    emissions.means = init_means_acc.array() / init_obs_count_acc_dbl.array();
    emissions.std_devs = (init_std_dev_acc.array() / init_obs_count_acc_dbl.array()).array().sqrt();
}

/*
 * Resets accumulators to 0 (or initializes them
 * if they haven't been yet).
 */
void HMM::baum_welch_reset_accumulators() {
    start_prior_acc.setZero(n_states);
    end_prior_acc.setZero(n_states);

    gamma_acc.setZero(n_states);
    xi_acc.setZero(n_states, n_states);

    obs_acc.setZero(n_states);
    obs_sq_acc.setZero(n_states);
}

/*
 * single iteration of baum welch
 */
void HMM::baum_welch_accumulate(const Eigen::VectorXd& obs) {
    size_t T = obs.size();

    Eigen::MatrixXd alpha = Eigen::MatrixXd::Zero(n_states, T);
    Eigen::MatrixXd beta = Eigen::MatrixXd::Zero(n_states, T);

    Eigen::MatrixXd B = emissions.pdf(obs);

    Eigen::VectorXd c = Eigen::VectorXd::Zero(T);
    forward(alpha, c, B);
    backward(beta, c, B);
    
    Eigen::MatrixXd gamma = Eigen::MatrixXd::Zero(n_states, T);
    compute_gamma(gamma, alpha, beta);

    Eigen::Tensor<double, 3> xi(T - 1, n_states, n_states);
    compute_xi(xi, alpha, beta, B);

    update_accumulators(gamma, xi, obs);
}

/*
 * Updates params using accumulators. baum welch
 * automatically updates the accumulators by aggregating
 * data. This step fills in params after an entire batch
 * has been accumulated.
 */
void HMM::baum_welch_summarize() {
    start_priors = start_prior_acc / start_prior_acc.sum();
    end_priors = end_prior_acc / end_prior_acc.sum();

    Eigen::VectorXd transp_norm = (gamma_acc.array() - end_prior_acc.array()).cwiseMax(HMM::FLOOR_VAL);
    transp = xi_acc.array().colwise() / transp_norm.array();
    
    emissions.means = obs_acc.array() / gamma_acc.array();
    Eigen::VectorXd variances = (obs_sq_acc.array() / gamma_acc.array()) - emissions.means.array().square();
    log_debug() << "variances \n" << variances.cwiseMax(HMM::FLOOR_VAL);
    emissions.std_devs = variances.cwiseMax(HMM::FLOOR_VAL).array().sqrt();
}


// overload ostream for clean print
std::ostream& operator<<(std::ostream& os, const HMM& hmm) {
    os << "Start prior probabilities: \n";
    os << hmm.get_start_priors() << "\n\n";

    os << "End prior probabilities: \n";
    os << hmm.get_end_priors() << "\n\n";

    os << "Transition probabilities \n";
    os << hmm.get_transp() << "\n\n";
    
    os << "Emission probabilities: \n";
    os << hmm.get_emissions() << "\n\n";

    return os;
}


// update_params old step
/*
// compute priors (start/end)
start_priors = gamma.col(0);
end_priors = gamma.col(gamma.cols() - 1);

// compute gamma normalization constant for each row (floor it to avoid div by 0 issues)
Eigen::VectorXd gamma_rownorm = gamma.rowwise().sum().cwiseMax(HMM::FLOOR_VAL);
Eigen::VectorXd gamma_rownorm_xi = gamma.leftCols(gamma.cols() - 1).rowwise().sum().cwiseMax(HMM::FLOOR_VAL);

// sum xi over time
std::array<int, 1> time_dim = {0};
Eigen::Tensor<double, 2> xi_sum_t = xi.sum(time_dim);

// compute new transp
Eigen::Map<Eigen::MatrixXd> xi_sum(xi_sum_t.data(), xi.dimension(1), xi.dimension(2));
transp = xi_sum.array().colwise() / gamma_rownorm_xi.array();

// compute mean
Eigen::VectorXd w_obs_mean = (gamma * obs).array() / gamma_rownorm.array();

// compute variance and std dev
Eigen::MatrixXd w_obs_mean_mat = w_obs_mean.replicate(1, obs.size());
Eigen::MatrixXd deviations = w_obs_mean_mat.rowwise() - obs.transpose();

Eigen::MatrixXd sq_deviations = deviations.array().square();
Eigen::MatrixXd sum_sq_deviations = (sq_deviations.array() * gamma.array()).rowwise().sum();

Eigen::VectorXd w_obs_var = sum_sq_deviations.array() / gamma_rownorm.array();
Eigen::VectorXd w_obs_std_dev = w_obs_var.array().sqrt().cwiseMax(HMM::FLOOR_VAL);

// reassign mean and std dev of all states
emissions.means = w_obs_mean;
emissions.std_devs = w_obs_std_dev;
*/

// old initialization step
// fill out prior probs
/*
start_priors.setZero(n_states);
start_priors[0] = 1.0;

// fill out end state probs
end_priors.setZero(n_states);
end_priors[n_states - 1] = 1.0;

transp.setZero(n_states, n_states);
// fill out transp matrix
for (size_t i = 0; i < n_states; ++i) {
    for (size_t j = 0; j < n_states; ++j) {
        if (j == i || j == i + 1) transp(i,j) = 0.5;
    }
}
// emission probs are filled in the constructor
*/

